apiVersion : apps/v1
kind: Deployment
metadata:
  name: "board-api-deploy"
  namespace: minipj
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "api"
  template:
    metadata:
      labels:
        app: "api"
    spec:
      containers:
        - name: "board-api"
          image: "minipj.azurecr.io/board-api"
          ports:
          - containerPort: 8080